### ISSUE TITLE
ToDo's

### ISSUE THREAD

**Issue by t3chn0m4g3** [telekom-security/tpotce#467]
- [x] Update Glutton to latest master
- [x] Update Heralding to 1.0.6
- [x] Update Cowrie to 2.x
- [x] Update Suricata to 5.x
- [x] Update ADBHoney to latest master with py3 support
- [x] Update Snare / Tanner to latest master
- [x] Update Conpot to latest master
- [x] ELK Stack, bump to latest 7.x
    - [x] Update Logstash Heralding's JSON logging, fields and dashboards
    - [x] Update Logstash new Suricata fields and dashboards
    - [x] Update Logstash new Cowrie fields and dashboards
- [x] Bump ELK stack to 7.x (disabled auth, feature for T-Pot 20.x)
- [x] Improve landing page (feature for T-Pot 20.x)
- [x] Rebuild all images and base on new 20.06 master
- [x] Dicompot: Logging

The following honeypots are missing Python 3.x support. Since Python 2.7 will be reaching EOL on 20200101 it is possible the following honeypots need removal from within T-Pot for the 20.x release (follow links to upstream tickets) following security considerations:
- [ ] [HoneyPy](https://github.com/foospidy/HoneyPy/issues/66), [Follow up](https://honeydb-agent-docs.readthedocs.io/en/latest/#installation)
- [ ] [RDPY](https://github.com/citronneur/rdpy/issues/91), however RDPY has a [fork ](https://github.com/hackdefendr/rdpy) with Py3 support.

## Other
- [x] Remove netselect-apt
- [x] Update Readme
- [x] Update Changelog
- [x] Merge dev to master incl. links
- [x] Update Readme
- [x] Update diagram and screenshots
- [x] Test upgrade from 19.03
- [x] Randomize Reboot times
- [ ] Improve HPTest script
- [ ] Support script

**Comment by iukea1** [comment]
Also mapping upgrade for 7.0  for the Elasticsearch indexes

**Comment by t3chn0m4g3** [comment]
@iukea1 Have you been working on that already?

**Comment by jrsanchezsilva** [comment]
Good night is for that reason does not show me the interface of kibana. (Buenas noches es por ese motivo no me muestra el interfaz de kibana.)

![image](https://user-images.githubusercontent.com/51901933/67536840-92d1cf00-f69e-11e9-9701-bf5307d2a4ca.png)

But the debian web interface does show me.  (Pero el interfaz web de debian si me muestra)

![image](https://user-images.githubusercontent.com/51901933/67536876-b3018e00-f69e-11e9-88ef-95c85753ad26.png)


![image](https://user-images.githubusercontent.com/51901933/67537030-4fc42b80-f69f-11e9-9436-94c26f57e801.png)

**Comment by t3chn0m4g3** [comment]
#531

**Comment by Blason** [comment]
I guess SMB honeypot should be high interactive. Passing UNC path it at least should pop-up username/password
